// Generated by CoffeeScript 1.6.3
(function() {
  var sprangularControllers;

  sprangularControllers = angular.module('sprangularControllers', ['sprangularServices', 'ngRoute', 'ui.router']);

  sprangularControllers.controller('productsController', [
    '$scope', '$state', '$stateParams', 'Product', 'Taxonomy', 'Defaults', function($scope, $state, $stateParams, Product, Taxonomy, Defaults) {
      $scope.root = Defaults.root;
      return Product.find($stateParams.id).$promise.then(function(response) {
        return $scope.currentProduct = response;
      });
    }
  ]);

  sprangularControllers.controller('taxonomiesController', [
    '$scope', '$state', '$stateParams', 'Taxonomy', 'Defaults', function($scope, $state, $stateParams, Taxonomy, Defaults) {
      var id;
      $scope.root = Defaults.root;
      id = [$stateParams.taxonomy];
      if ($stateParams.taxon) {
        id.push($stateParams.taxon);
      }
      return Taxonomy.findByPermalink(id).then(function(response) {
        var taxon, taxonomy;
        if ($stateParams.taxon) {
          taxon = response[1];
          $scope.title = taxon.name;
          return Taxonomy.listProducts(taxon.id).$promise.then(function(response) {
            return $scope.products = response.products;
          });
        } else {
          taxonomy = response[0];
          $scope.title = taxonomy.name;
          return $scope.taxons = taxonomy.taxons;
        }
      });
    }
  ]);

  sprangularControllers.controller('storeView', [
    '$scope', '$state', '$stateParams', 'Taxonomy', 'Defaults', function($scope, $state, $stateParams, Taxonomy, Defaults) {
      $scope.path = Defaults.root + $state.current.url + '/taxonomies/';
      Taxonomy.taxonomies_with_meta().$promise.then(function(response) {
        return $scope.taxonomies = response.taxonomies;
      });
      return console.log($state);
    }
  ]);

}).call(this);
