// Generated by CoffeeScript 1.6.3
(function() {
  var sprangularServices;

  sprangularServices = angular.module('sprangularServices', ['ngResource']);

  sprangularServices.service('Defaults', function() {
    return {
      root: 'http://0.0.0.0:3000/#/',
      api_url: "http://0.0.0.0:3000/api/"
    };
  });

  sprangularServices.factory('Product', function($resource, Defaults) {
    var Product;
    return Product = (function() {
      function Product() {
        this.service = $resource(Defaults.api_url + 'products/:id', {
          id: '@id'
        });
      }

      Product.products_with_meta = function() {
        var service;
        service = $resource(Defaults.api_url + 'products');
        return service.get();
      };

      Product.find = function(id) {
        var service;
        service = $resource(Defaults.api_url + 'products/:id', {
          id: id
        });
        return service.get();
      };

      return Product;

    })();
  });

  sprangularServices.factory('Taxonomy', function($resource, $http, Defaults) {
    var Taxonomy;
    return Taxonomy = (function() {
      function Taxonomy() {
        this.service = $resource(Defaults.api_url + 'taxonomies/:id', {
          id: '@id'
        });
      }

      Taxonomy.taxonomies_with_meta = function() {
        var service;
        service = $resource(Defaults.api_url + 'taxonomies');
        return service.get();
      };

      Taxonomy.find = function(id) {
        var service;
        if (id.length > 1) {
          service = $resource(Defaults.api_url + 'taxonomies/' + id[0] + '/taxons/' + id[1]);
        } else {
          service = $resource(Defaults.api_url + 'taxonomies/' + id[0]);
        }
        return service.get();
      };

      Taxonomy.findByPermalink = function(permalink) {
        return this.taxonomies_with_meta().$promise.then(function(response) {
          var current_taxon, current_taxonomy;
          current_taxonomy = null;
          current_taxon = null;
          angular.forEach(response.taxonomies, function(taxonomy) {
            taxonomy = taxonomy.root;
            if (taxonomy.permalink === permalink[0]) {
              current_taxonomy = taxonomy;
            }
            if (permalink[1]) {
              return angular.forEach(taxonomy.taxons, function(taxon) {
                if (taxon.permalink === permalink[0] + '/' + permalink[1]) {
                  return current_taxon = taxon;
                }
              });
            }
          });
          return [current_taxonomy, current_taxon];
        });
      };

      Taxonomy.listProducts = function(taxon_id) {
        var service;
        service = $resource(Defaults.api_url + 'products?q[classifications_taxon_id_in]=' + taxon_id);
        return service.get();
      };

      return Taxonomy;

    })();
  });

}).call(this);
